### ISSUE TITLE
[+] IP Tracker

### ISSUE THREAD

**Issue by nsde** [Konnor88/anti-grabify#20]
**ikwyd.com** is a domain which allows people to "can see what [a friend] downloads in bittorrent network", also tracking the visitor's IP:
https://iknowwhatyoudownload.com/en/link/

**Comment by Konnor88** [comment]
Hi, I have added the tracking link that the website uses. I will push it out to the web store versions soon and will close the issue once its published.

**Comment by Konnor88** [comment]
Ok, Google and Mozilla have approved the update and its now live on their web stores.
