### ISSUE TITLE
Suggestion - Ublock Origin block list

### ISSUE THREAD

**Issue by robertheadley** [Konnor88/anti-grabify#3]
I would suggest that in addition to your own software, you consider making a blocklist for ublock origin that users can subscribe to.

I manually took the domains from your extension and added them to my ublock, but it would be better if it was a regularly updated subscription. Assuming that is something that you plan to do.

**Comment by Konnor88** [comment]
Hi there. Sure, I will add a URL list text file that can be imported into uBlock Origin inside the repository. I will be sure to regularly update that text file as well.

**Comment by Elaborendum** [comment]
@Konnor88 Please, could you also add a title to the file? Something like "Anti-Grabify List" would be nice, currently when it's added it just shows the URL.
