### ISSUE TITLE
I Don't get the anti-grabify prompt when going to tracker.iplocation.net

### ISSUE THREAD

**Issue by CJStyles123** [Konnor88/anti-grabify#5]
I Don't get prompted the Anti Grabify when going to tracker.iplocation.net even though it's added in the list, Was something missing?

**Comment by Konnor88** [comment]
Hi, are you using the version from the Chrome Web Store? Google currently is still reviewing the latest version, which can take up to a few days before its updated on the Chrome store.

**Comment by CJStyles123** [comment]
Correct! I'm using the extension from the Chrome Webstore, Thank you for your response and i'll wait.
