### ISSUE TITLE
any plans to remove dead links and to label where urls are from?

### ISSUE THREAD

**Issue by CJStyles123** [Konnor88/anti-grabify#7]
i think dead links should be removed and other urls should be labeled to where they're from etc so it's easier for all of us. (you can do this when you have alot of time)

**Comment by Konnor88** [comment]
Hi, I've also been thinking of what to do with the dead links on the extension since some of those links have gone inactive. I will definitely be doing a cleanup on all those dead links when I get the chance and try to label where the current links are from.

**Comment by Konnor88** [comment]
UPDATE: I just cleaned up the URL list for uBlock Origin and labeled the sources of the alive links. I have also removed the dead links from the block list. I will be publishing it to the web store ASAP.
