### ISSUE TITLE
Suggestion - PiHole DNS List

### ISSUE THREAD

**Issue by ickfosec** [Konnor88/anti-grabify#9]
First off thanks for this project! I was looking for some IP grabber blocklists to add to a PiHole DNS setup and came across this. While I can write a script that will grab the URL list from this repo and re-package it as a PiHole formatted blocklist file, it might be beneficial for others to have access to it as well.

If you did offer the URL list in a PiHole DNS blocklist format, people could simply add https://raw.githubusercontent.com/Konnor88/anti-grabify/master/<file\>.txt to their PiHole configurations and automatically get their blocklists updated. The benefit of this is getting blocking on other devices such as smartphones and tablets that may not be able to run browser extensions. 

I understand that this is likely venturing outside the scope of your initial intentions for this project so I can understand either way. Thank you!

**Comment by Konnor88** [comment]
Hi, I apologize for not replying earlier this week. Sure, that doesn't seem like a bad idea. I have added a PiHole DNS list inside the repository.
